# Test your FastAPI endpoints

GET http://127.0.0.1:8000/classify/test, but Hey i think you re a fucking bitch?model=bert
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
